agentService/agent/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from .import views, restviews
from rest_framework import routers
from .commons import *
from .views import GeneratePdf
# rest web services
from .restviews import AgentImageAPIView

router = routers.DefaultRouter()

urlpatterns=[

    path('pdf/', GeneratePdf.as_view(),name='pdfConvert'),
    path('pdf_create/', views.pdf_create,name='pdf_create'),
    path('rest/', include(router.urls)),
    path('rest/getAgents/photo', AgentImageAPIView.as_view(),name="getagent-page"),
    path('rest/search/', restviews.search,name="search"),
    path('rest/auto_search/',restviews.auto_search ,name="auto_search"),
    path('getKey/', views.getKey, name="getKey"),
    path('', views.handleShowAgent, name="agentLoginHome"),
    #path(url_dict["index"], views.index, name="index"),
    path('search_url/', views.search_url, name="search_url"),
    path(url_dict["Create Agent"], views.handleAgent, name="Create Agent"),
    path(url_dict["Show Agents"], views.showAgents, name="Show Agents"),
    path(url_dict["Search Agent"], views.searchByAgent, name="Search Agent"),
    path(url_dict["advSearch"], views.advSearchByAgent, name="advSearch"),
    path('agentLogin/', views.agentLogin, name="agentLogin"),
    path('agentLogout/', views.agentLogout, name="logout-page"),
    path('imageUpload/', views.imageUpload,name="imageUpload"),
    #path('supervisorImageUpload/', views.supervisorImageUpload,name="superUserImageUpload-page"),
    path(url_dict["MY Profile"], views.agentDetails, name="MY Profile"),
    path('editProfile/', views.editProfile, name="edit-page"),
    path('changePassword/', views.changePassword, name="changePassword-page"),
    path(url_dict["Create Department"], views.createDepartment, name="createDepartment"),
    path(url_dict["Show Departments"], views.showAllDepartments, name="Show Departments"),
    path('createRequest/', views.createRequest, name="createRequest"),
    path(url_dict["Show Requests"], views.showRequests, name="Show Requests"),
    #path('supervisorDetails/', views.supervisorDetails, name="showSupervisor-page"),

    path('<requestedBy>/unlockRequest/', views.unlockRequest, name="unlockRequest"),
    path('<int:id>/imageData/', views.imageData, name="imageData"),
    path('<dept>/deptData/', views.deptData, name="deptData"),
    path(url_dict["Search Department"],views.searchByDepartment,name="Search Department"),
    path('createAddress/', views.createAddress, name="createAddress"),
    path('pAddressUpdate/', views.pAddressUpdate, name="pAddressUpdate"),
    path(url_dict["Create Partner"], views.partnerCreate, name="createPartner"),
    path(url_dict["Search Partner"], views.partnerSearch, name="partnerSearch"),
    path(url_dict["Update Partner"], views.partnerUpdate, name="partnerUpdate"),
    path('partnerUpdateSubmit/', views.partnerUpdateSubmit, name="partnerUpdateSubmit"),
    path('partnerLiveSearch/',views.partnerLiveSearch,name="partnerLiveSearch"),
    path('showPartners/',views.showPartners,name="showPartners"),
    path('createbranch/',views.createbranch,name="createbranch-page"),
    path('searchbranch/',views.searchbranch,name="searchbranch-page"),
    path('branchUpdate/',views.branchUpdate,name="branchUpdate-page"),
    path('branchUpdateSubmit/',views.branchUpdateSubmit,name="branchUpdateSubmit-page"),
    path('branchLiveSearch/',views.branchLiveSearch,name="branchLiveSearch-page"),
    path('invoiceSelect/',views.invoiceSelect,name="invoiceSelect"),
    path('invoiceCreate/',views.invoiceCreate,name="invoiceCreate"),

    #path('partnerAdvSearch/', views.partnerAdvSearch, name="partnerAdvSearch"),
    #path('createTaddress/', views.createTaddress, name="createTaddress"),
    #path('showAllDepartments/', views.showAllDepartments, name="showAllDepartments-page"),
    #path('searchByDepartment/', views.searchByDepartment, name="showAllDepartments-page"),
]

agentService/agentService/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('agent/',include(('agent.urls','agent'),namespace='agent')),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

agentService/agent/models.py
from django import forms
from django.db import models
from django.utils import timezone

# Create your models here.
# Model class

AddressOptions = (('PermanentAddress', 'PermanentAddress'), ('TemporaryAddress', "TemporaryAddress"))

class AgentTable(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    firstName = models.CharField(max_length=8, default="")
    lastName = models.CharField(max_length=30)
    username = models.CharField(max_length=20, unique=True, null=False)
    password = models.CharField(max_length=20, null=False)
    dept = models.CharField(max_length=30, blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    email = models.EmailField(max_length=20, unique=True, default="", null=False)
    image = models.ImageField(blank=True, null=True, default='0')
    updated_date = models.DateTimeField(auto_now=True)
    created_by = models.CharField(max_length=30, null=True)
    #confirmPassword = models.CharField(max_length=20, null=False, default='')
    count = models.IntegerField(blank=True, default=0)
    usertype = models.CharField(max_length=30,default='')

    def __str__(self):
        return self.username


class Department(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    deptName = models.CharField(max_length=30, null=True)
    createdBy = models.ForeignKey(AgentTable, on_delete=models.CASCADE, default='')
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.deptName

class Requests(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    requestedUserName = models.CharField(max_length=30, null=True)
    requestedBy = models.ForeignKey(AgentTable,null=True, blank=True, on_delete=models.CASCADE)
    requestedDate = models.DateTimeField(default=timezone.now)
    approvedBy = models.CharField(max_length=30, default='', null=True)
    approvedDate = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=30, null=True)
    description = models.CharField(max_length=200, null=True)
    requestType = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.requestedBy

class LogTable(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    loginTime=models.DateTimeField()
    logoutTime=models.DateTimeField(null=True)
    sessionId=models.IntegerField(default='')
    agentId=models.IntegerField(default=0)
    def __str__(self):
        return self.loginTime

class AddressBase(models.Model):
    Dno = models.CharField(max_length=10,default='')
    Street = models.CharField(max_length=20,default='')
    City = models.CharField(max_length=20,default='')
    State = models.CharField(max_length=20,default='')
    Country=models.CharField(max_length=20,default='')
    Pincode = models.CharField(max_length=6,default='')

    class Meta:
        abstract = True
        ordering = ['Dno','Street','City','State','Country','Pincode']

class Partner(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    name =models.CharField(max_length=40,default='')
    code =models.CharField(max_length=40,default='')
    GSTCode = models.CharField(max_length=40,default='')
    IGST = models.CharField(max_length=40, default='', null=True)
    CGST = models.CharField(max_length=40, default='', null=True)
    createdBy = models.ForeignKey(AgentTable, on_delete=models.CASCADE, default='')
    created_date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.name

class Branch(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    BranchName =models.CharField(max_length=40,default='')
    BranchCode =models.CharField(max_length=40,default='')
    GSTid = models.CharField(max_length=40,default='')
    igst = models.CharField(max_length=40, default='', null=True)
    cgst = models.CharField(max_length=40, default='', null=True)
    createdBy = models.ForeignKey(AgentTable, on_delete=models.CASCADE, default='')
    created_date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.BranchName

class MyAddressTable(AddressBase):
    id = models.AutoField(auto_created=True, primary_key=True)
    agent_id = models.ForeignKey(AgentTable, on_delete=models.CASCADE, default='',blank=True,null=True)
    AddressType = models.CharField(max_length=30, choices=AddressOptions,blank=True,null=True)
    partner_id= models.ForeignKey(Partner,on_delete=models.CASCADE, default='',blank=True,null=True)
    branch_id= models.ForeignKey(Branch, on_delete=models.CASCADE, default='',blank=True,null=True)

    def __str__(self):
        return self.Dno


class Invoice(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    invoiceSummary = models.CharField(max_length=200, default='')
    invoiceNumber = models.CharField(max_length=40, default='')
    partner = models.CharField(max_length=40, default='')
    branch = models.CharField(max_length=40, default='')
    created_date = models.DateTimeField(default=timezone.now)
    TransportCharges = models.CharField(max_length=40, default='', null=True)
    TotalTaxAmount = models.CharField(max_length=40, default='', null=True)
    TotalCost = models.CharField(max_length=40, default='', null=True)
    status = models.CharField(max_length=40, default='',null=True)


class InvoiceProduct(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    Description = models.CharField(max_length=40, default='')
    HSNCode = models.CharField(max_length=40, default='', null=True)
    UOM = models.CharField(max_length=40, default='', null=True)
    QtyPerKg = models.CharField(max_length=40, default='')
    RatePerKg = models.CharField(max_length=40, default='')
    TotalQtyCost = models.CharField(max_length=40, default='')
    TotalTax = models.CharField(max_length=40, default='', null=True)
    invoiceProduct = models.ForeignKey(Invoice, on_delete=models.CASCADE, default='', blank=True, null=True)

agentService/agent/forms.py
from django.forms import ModelForm
from .models import AgentTable, Requests, Department, MyAddressTable, Partner, Branch
from django import forms


from django.core.exceptions import NON_FIELD_ERRORS


# ModelForm class
OPTIONS = (("agent", "agent"), ("supervisor", "supervisor"),("sales manager","sales manager"))
class AgentForm(forms.ModelForm):

    firstName = forms.CharField(widget=forms.TextInput(attrs={'class': 'firstName','id': 'firstName'}),required=True)
    lastName = forms.CharField(widget=forms.TextInput(attrs={'class': 'lastName','id': 'lastName'}),required=True)
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'email', 'id': 'email'}),required=True)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'username','id': 'username' ,'placeholder': ''}),required=True)
    password = forms.CharField(widget=forms.PasswordInput (attrs={'class': 'password', 'id': 'password'}),required=True)
    confirmPassword = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'confirmPassword', 'id': 'confirmPassword'}),required=True)
    dept=forms.ModelChoiceField(queryset=Department.objects.all(), initial=0,widget=forms.Select(attrs={'class':'dept-select'}),required=True)
    usertype=forms.ChoiceField(choices=OPTIONS,widget=forms.Select(attrs={'class':'usertype-select'}),required=True)
    # specify the name of model to use
    class Meta:
        model = AgentTable
        fields = ["firstName", "lastName", "email","username","password","confirmPassword","dept","usertype"]

class ImageForm(forms.Form):
    """Image upload form."""
    image = forms.ImageField()

class DepartmentForm(forms.ModelForm):

    deptName= forms.CharField(widget=forms.TextInput(attrs={'class': 'deptName','id': 'deptName'}))
    class Meta:
        model=Department
        fields=["deptName"]


class RequestsForm(forms.ModelForm):
    requestedUserName = forms.CharField(widget=forms.TextInput(attrs={'class': 'requestedUserName', 'id': 'requestedUserName'}))
    description = forms.CharField(widget=forms.Textarea
        (attrs={'class': 'description','id': 'description'}))

    OPTIONS = [('IT','IT'),('Recruitment','Recruitment'),('Finance','Finance')]
    requestType  = forms.ChoiceField(required=True, choices=OPTIONS,widget=forms.Select
        (attrs={'class': 'requestType','id': 'requestType'}))
    class Meta:
        model = Requests
        fields = ["requestedUserName","description", "requestType"]
class AddressForm(forms.ModelForm):
    Dno = forms.CharField(widget=forms.TextInput(attrs={'class': 'dno', 'id':'dno'}))
    Street = forms.CharField(widget=forms.TextInput(attrs={'class': 'street', 'id': 'street'}))
    City = forms.CharField(widget=forms.TextInput(attrs={'class': 'city', 'id': ' city'}))
    State = forms.CharField(widget=forms.TextInput(attrs={'class': 'state', 'id': 'state'}))
    Pincode = forms.CharField(widget=forms.TextInput(attrs={'class': 'pincode', 'id': 'pincode'}))

    class Meta:
        model=MyAddressTable
        fields=["Dno","Street","City","State","Pincode","AddressType","agent_id","partner_id","branch_id"]

class PartnerForm(forms.ModelForm):
    class Meta:
        model=Partner
        fields = ["name", "code", "GSTCode"]

class BranchForm(forms.ModelForm):
    class Meta:
        model=Branch
        fields=["BranchName","BranchCode","GSTid","igst","cgst"]

agentService/agent/templates/branchSearch.html
{% extends "agentDetails.html" %}
{% block code %}
 {% load static %}
 <link rel="stylesheet" type="text/css" href="{% static 'css/branch.css' %}">

            <div>
               <form action="/agent/searchbranch/"  method="post" >
                         {% csrf_token %}
                    <div class="searchbranch-field">
                         {{msg}}
                        </div>
                   <div>
                       <label class="search-branch-field">Search</label>
                        <input type="text" id="placeholder" name="branch" placeholder="Enter branchname" class="branch-field-input" required/>

                    </div>
                    <div class="searchbranch">
                        <input type="submit" value="Search" id="button-1" class="searchbranch-button">
                    </div>
           	   </form>
            </div>

    <div>

        <table id="search-by-branch-table">
            {% if searchbranch %}
            <tr>
                <td>
                     Details of {{searchbranch.BranchName}}
                </td>
            </tr>

            <tr>
                <th>
                    BranchName
                </th>
                 <th>
                    CreatedBy
                </th>
                <th>
                    CreatedDate
                </th>
            </tr>
            <tr>
                <td>
                    {{searchbranch.BranchName}}
                </td>

                <td>
                     {{searchbranch.createdBy}}
                </td>
                 <td>
                     {{searchbranch.created_date}}
                 </td>
            </tr>

        </table>
        {% endif %}
    </div>
{% endblock %}

agentService/agent/templates/createbranch.html
{% extends "agentDetails.html" %}
{% block code %}
 {% load static %}

        <link rel="stylesheet" type="text/css" href="{% static 'css/branch.css' %}">
    <div class="column middle">
        <span class="error_form" id="error_message">{{msg}}</span>
        <form action="/agent/createbranch/" name="createbranch-page" method="post">
            {% csrf_token %}
            <div class="branch-field-container">
                <div class="branch-field">
                   <label class="branch-field-label">BranchName</label>
                    {{form.BranchName}}</br>
		   <label class="branch-field-label">BranchCode </label>
                    {{form.BranchCode }}</br>
		   <label class="branch-field-label">GSTid</label>
                    {{form.GSTid}}</br>

                    <input type="submit" value="Create" class="branch-field-button">
               </div>
           </div>

        </form>

  </div>

{% endblock %}

agentService/agent/templates/editProfile.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Update Profile</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
<link rel="stylesheet" href="style.css">

	<link rel="stylesheet" type="text/css" href="{% static 'css/profiledetails.css' %}">
        <script src="{% static 'js/imageUpload.js' %}"></script>
        <script src="{% static 'js/resetPassword.js' %}"></script>
        <script src="{% static 'js/updateProfile.js' %}"></script>

</head>
<body>

<div class="header">
    <span>last successful login:{{last_login}}</span>
  <h1 class="welcome">Welcome {{request.session.firstName}}</h1>
</div>
<div class="topnav">
   	   <a href="/agent/agentProfile/">My Profile</a>

        {% if agentProfile.usertype == "supervisor" %}
             <div class="dropdown">
                      <button class="dropbtn">Agent</button>
                      <div class="dropdown-content">
                      <a href="/agent/register/">Create Agent</a>
                      <a href="/agent/showAgents/">ShowAgents</a>
                      <a href="/agent/searchByAgent/">Search</a>
                      </div>
                   </div>
                   <div class="dropdown">
                      <button class="dropbtn">Department</button>
                      <div class="dropdown-content">
                      <a href="/agent/createDepartment/">Create Department</a>
                      <a href="/agent/showAllDepartments/">ShowAllDepartments</a>
                      <a href="/agent/searchByDepartment/">SearchByDepartment</a>
                      </div>
                   </div>
                   <div class="dropdown">
                      <button class="dropbtn">Requests</button>
                      <div class="dropdown-content">

                      <a href="/agent/showRequests/">ShowRequests </a>
                      </div>
                   </div>
        {% endif %}
       <a href="/agent/agentLogout/">Logout</a>
</div>

<div class="row">
    <div class="column side left">
             <div class="display-image">
                    {% if agentProfile.image %}
                        <img src="{{agentProfile.image.url}}" alt="MyImage" accept=".png,.jpg,.jpeg" width="200px" height="150px"/>
                    {% else %}

                    {% endif %}
                </div>

                <div class="field-update" >
                <input type="submit" value="UpdateImage"  onclick="myImageUpload()" id="updateImage-btn" class="updateImage-btn" style="display:block"/>
                </div>
                <div>
                    <div id="upload" style="display:none;">
                        <form action='/agent/upload/' method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="field">
                                <input id="id_image" type="file" class="profile-image" name="image">
                        </div>

                        <div class="field">
                        <input type="submit" value="Upload" class="profile-image-upload-btn" />
                        </div>
                        </form>
                    </div>
                </div>
          </div>

    <div class="column middle">

    <div class="update-profile-container">

           <form action="/agent/editProfile/" method="post">
                    {% csrf_token %}
               {{msg}}
                <div class="update-field">
                    <label class="update-field-label">First Name</label>
                    <input type="text" name="firstName" id="firstName" class="editProfile-firstName"
					value="{{editProfile.firstName}}" />
                </div>
                <div class="update-field">
                    <label class="update-field-label"> Last Name</label>
                    <input type="text" name="lastName" id="lastName" class="editProfile-firstName"
					value="{{editProfile.lastName}}" />
                </div>
                <div class="update-field">
                    <label class="update-field-label">Email Id</label>
                    <input type="text" name="email" id="email" class="editProfile-email"
					value="{{editProfile.email}}" />
                </div>

                <div class="field">
                    <input type="submit" value="Edit" class="update-profile-submit" >
                </div>

         </form>
    </div>
    </div>

  <div class="column side right">
      <ul class='tabs-buttons'>
            <!--    <td>
                    <li><a href="/agent/editProfile/" id='tab1-updateProfile'>UpdateProfile</a></li>
                </td>-->
                <td>
                    <li><a href="/agent/changePassword/" id='tab2-changePassword'>ChangePassword</a></li>
                </td>
            </ul>

  </div>
</div>
</div>
<div class="footer">
  <p>Footer</p>
</div>
</body>
</html>

agentService/agent/templates/invoiceSelect.html
{% extends "agentDetails.html" %}
{% block code %}
        {% load static %}
                <link rel="stylesheet" type="text/css" href="{% static 'css/invoice.css' %}">

<div class="Invoice-Select-Container">
    <form action="/agent/invoiceSelect/" method="post">
         {% csrf_token %}
    <table>
        <tr>
            <td>
    <div class="Invoice-selection">
           <span>Invoice created from Branch
            <select id="invoice-branch-select" name="branch">
                <option  value="" selected="selected">---SELECT---</option>
            {% for branch in branch_Obj %}
                   <option>
                       {{branch.BranchName}}
                   </option>
            {% endfor %}
            </select></span>
    </div>
          </td>
          <td>
    <div class="Invoice-selection">
            <span>To Partner
            <select id="invoice-partner-select" name="partner">
                <option  value="" selected="selected">---SELECT---</option>
            {% for partner in partner_Obj %}
                   <option>
                       {{partner.name}}
                   </option>
            {% endfor %}
            </select></span>
       </div>
            </td>
        </tr>
     </table>
        <input type="submit" name="submit" value="Submit" id="invoice-select-submit" class="invoice-select-submit">
    </form>
</div>


{% endblock %}

agentService/agent/templates/showAgents.html
{% extends "agentDetails.html" %}
{% block code %}
        <table id="agent">
            <tr><td>List Of Agents</td></tr>
            <tr>
                 <th>Image</th>
                 <th>FirstName</th>
                 <th>LastName</th>
                 <th>Email</th>
                 <th>Username</th>
                 <th>UserType</th>
                 <th>Department</th>
            </tr>
           {% for show_agent_obj in page_obj %}
            <tr>
            <td>
                    {% if show_agent_obj.image %}
                    <a href="{% url 'agent:imageData' id=show_agent_obj.id %}"><img src="{{show_agent_obj.image.url}}" alt="MyImage" accept=".png,.jpg,.jpeg"
                                                width="70px" height="25px"/>  </a>
                     {% else %}
                            {{msg}}
                    {% endif %}
            </td>
            <td>
                    {{show_agent_obj.firstName}}
            <td>
                        {{show_agent_obj.lastName}}
            </td>
            <td>
                 {{show_agent_obj.email}}
            </td>
            <td>
                 {{show_agent_obj.username}}

            </td>
            <td>
             {{show_agent_obj.usertype}}
            </td>
            <td>
       <a href="{% url 'agent:deptData' dept=show_agent_obj.dept %}">{{show_agent_obj.dept}}</a>
            </td>
            </tr>
             {% endfor %}
       </table>
       <div class="pagination">
          <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">&laquo; previous</a>
            {% endif %}
          </span>
          <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
          </span>
          </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.paginator.num_pages }}">last  &raquo;</a>
                <a href="?page={{ page_obj.next_page_number }}">next  &raquo;</a>
            {% endif %}
          </span>
       </div>
{% endblock%}

agentService/agent/templates/supervisorDetails.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Agent Details</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/profiledetails.css' %}">
        <script src="{% static 'js/imageUpload.js' %}"></script>
        <script src="{% static 'js/resetPassword.js' %}"></script>
        <script src="{% static 'js/updateProfile.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/imageUpload.css' %}">
</head>
<body>

        <div class="header">
          <h1 class="welcome">Welcome {{request.session.firstName}}</h1>
        </div>
        <div class="topnav">
               <a href="/agent/supervisorDetails/">My Profile</a>

                 <div class="dropdown">
                      <button class="dropbtn">Agent</button>
                      <div class="dropdown-content">
                      <a href="/agent/register/">Create Agent</a>
                      <a href="/agent/showAgents/">ShowAgents</a>
                      <a href="/agent/searchByAgent/">SearchByAgent</a>
                      </div>
                   </div>
                   <div class="dropdown">
                      <button class="dropbtn">Department</button>
                      <div class="dropdown-content">
                      <a href="/agent/createDepartment/">Create Department</a>
                      <a href="/agent/showAllDepartments/">ShowAllDepartments</a>
                      <a href="/agent/searchByDepartment/">SearchByDepartment</a>
                      </div>
                   </div>
                   <div class="dropdown">
                      <button class="dropbtn">Requests</button>
                      <div class="dropdown-content">

                      <a href="/agent/showRequests/">ShowRequests </a>
                      </div>
                   </div>
                  <a href="/agent/agentLogout/">Logout</a>
        </div>
        <div class="row">
          <div class="column side">
             <div class="display-image">
                    {% if supervisor_detail_obj.image %}
                        <img src="{{supervisor_detail_obj.image.url}}" alt="MyImage" accept=".png,.jpg,.jpeg" width="200px" height="150px"/>
                    {% else %}
                        {{msg}}
                    {% endif %}
             </div>

              <div class="field-update" >
                <input type="submit" value="UpdateImage"  onclick="myImageUpload()" id="updateImage-btn" style="display:block"/>
              </div>
                <div>
                    <div id="upload" style="display:none;">
                        <form action='/agent/supervisorImageUpload/' method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                    <div class="field">
                                <input id="id_image" type="file" class="profile-image" name="image">
                        </div>

                        <div class="field">
                        <input type="submit" value="Upload" class="profile-image-btn" />
                        </div>
                        </form>
                    </div>
                </div>
          </div>

        <div class="column middle">
            <div id="profile-details" style="display:block" class="profile-details-container">
                <table id="agent">
                    <tr>
                    <h2 style="text-align:center">Profile Details</h2>
                    </tr>
                    <tr>
                       <td>
                          <label>First Name:</label>
                       </td>
                          <td>
                            <div class="field">

                    {{supervisor_detail_obj.firstName}}
                        </div>
                        </td>
                        </tr>
                    <tr>
                        <td>
                            <label> Last Name:</label>
                       </td>
                      <td>
                        <div class="field">

                    {{supervisor_detail_obj.lastName}}
                         </div>
                            </td>
                        </tr>
                        <tr>
                        <td>
                           <label>Email Id:</label>
                       </td>

                        <td>
                         <div class="field">

                    {{supervisor_detail_obj.email}}
                        </div>
                            </td>
                            </tr>
                    <tr>
                        <td>
                           <label>UserName</label>
                       </td>
                         <td>
                        <div class="field">

                    {{supervisor_detail_obj.username}}
                        </div>
                             </td>
                        </tr>



                    <tr>

                       <td>
                             <label>Department:</label>
                       </td>

                        <td>
                        <div class="field">

                            {{supervisor_detail_obj.dept}}
                        </div>
                         </td>
                    </tr>
                </table>
                      </div>
            </div>

          <div class="column side">

        </div>
        </div>
        <div class="footer">
          <p>Footer</p>
        </div>
</body>
</html>